name: "Main Build"

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # the nebula plugin used in this repo needs the tags
          fetch-depth: 0

      - id: setup-java-17
        name: Setup Java 17
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: temurin
          java-version: 17

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2

      - name: Build
        run: >
          ./gradlew build --stacktrace
          "-Porg.gradle.java.installations.paths=${{ steps.setup-java-17.outputs.path }}"

      - name: Publish snapshot
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        run: >
          ./gradlew snapshot --stacktrace
          "-Porg.gradle.java.installations.paths=${{ steps.setup-java-17.outputs.path }}"
