name: "Main Build"

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          # the nebula plugin used in this repo needs the tags
          fetch-depth: 0

      - id: setup-java-17
        name: Setup Java 17
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: temurin
          java-version: 17

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Build
        run: >
          ./gradlew build --stacktrace
          "-Porg.gradle.java.installations.paths=${{ steps.setup-java-17.outputs.path }}"

      - name: Publish snapshot
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        run: >
          ./gradlew snapshot --stacktrace
          "-Porg.gradle.java.installations.paths=${{ steps.setup-java-17.outputs.path }}"
